<?php

/**
 * Service pricing packages from public/EmCa_Tech_Pricing_Package.pdf (2026).
 * Prices are starting rates in TZS; final quotes after free consultation.
 */
return [
    'meta' => [
        'title' => 'Service Pricing Package',
        'year' => 2026,
        'currency' => 'TZS',
        'usd_rate' => 2650, // fallback if live fetch fails
        'usd_rate_note' => 'Indicative conversion only. Final invoices may use the rate on payment day.',
        'document' => 'EmCa_Tech_Pricing_Package.pdf',
        'document_ref' => 'EMCA-PRICE-2026-v1',
        'intro' => 'Transparent starting prices for software, web, graphics, ICT consultancy, infrastructure & tourism tools. Final quotations are tailored after a free consultation based on scope, users, customization, and support level.',
        'disclaimer' => 'Prices shown are starting rates for standard scope. Custom features, extra users, multi-branch setups, travel outside Moshi, third-party licenses, and hardware are quoted separately. Flexible packages and phased payments are available for schools and non-profits. VAT / applicable taxes may apply as per Tanzanian law.',
        'banner' => 'images/Service_banner.jpg',
    ],

    'exchange' => [
        'cache_minutes' => 720, // refresh about twice a day
        'timeout_seconds' => 8,
        'endpoints' => [
            [
                'source' => 'open.er-api.com',
                'url' => 'https://open.er-api.com/v6/latest/USD',
                'tzs_path' => 'rates.TZS',
            ],
            [
                'source' => 'exchangerate-api.com',
                'url' => 'https://api.exchangerate-api.com/v4/latest/USD',
                'tzs_path' => 'rates.TZS',
            ],
        ],
    ],

    'services' => [
        'web-development' => [
            'name' => 'Web Development',
            'icon' => 'fas fa-globe',
            'description' => 'Complete web solutions, design, development, hosting, SEO, and ongoing management for schools, businesses, and institutions.',
            'packages' => [
                [
                    'name' => 'Starter Website',
                    'includes' => 'Up to 5 pages, responsive design, contact form, basic SEO, 1 revision round',
                    'amount' => 450000,
                    'period' => '',
                    'price' => 'From TZS 450,000',
                ],
                [
                    'name' => 'Business Website',
                    'includes' => 'Up to 10 pages, CMS (easy content updates), gallery/blog, SEO setup, 2 revisions',
                    'amount' => 850000,
                    'period' => '',
                    'price' => 'From TZS 850,000',
                ],
                [
                    'name' => 'E-Commerce Website',
                    'includes' => 'Product catalog, cart & checkout, M-Pesa/payment ready, admin panel, training',
                    'amount' => 1800000,
                    'period' => '',
                    'price' => 'From TZS 1,800,000',
                ],
                [
                    'name' => 'Custom Web Portal',
                    'includes' => 'User accounts, dashboards, APIs, role-based access, built to your workflow',
                    'amount' => 2500000,
                    'period' => '',
                    'price' => 'From TZS 2,500,000',
                ],
                [
                    'name' => 'Website Redesign',
                    'includes' => 'Modern rebuild of an existing site with improved UX, speed & mobile layout',
                    'amount' => 650000,
                    'period' => '',
                    'price' => 'From TZS 650,000',
                ],
                [
                    'name' => 'Hosting & Domain (Annual)',
                    'includes' => 'Secure hosting, SSL, email setup, backups & uptime monitoring',
                    'amount' => 180000,
                    'period' => '/ yr',
                    'price' => 'From TZS 180,000 / yr',
                ],
                [
                    'name' => 'Website Maintenance',
                    'includes' => 'Updates, security patches, content edits (up to 4 hrs/month)',
                    'amount' => 80000,
                    'period' => '/ mo',
                    'price' => 'From TZS 80,000 / mo',
                ],
                [
                    'name' => 'SEO Package',
                    'includes' => 'On-page SEO, Google Business, keyword research & monthly report',
                    'amount' => 150000,
                    'period' => '/ mo',
                    'price' => 'From TZS 150,000 / mo',
                ],
            ],
        ],

        'software-solutions' => [
            'name' => 'Software Solutions',
            'icon' => 'fas fa-laptop-code',
            'description' => 'Practical management systems trusted by schools, shops, churches, hostels, and cooperatives across Tanzania. Prices below are setup / license starting packages; annual support is optional.',
            'packages' => [
                [
                    'name' => 'ShuleXpert Basic',
                    'includes' => 'School management: students, attendance, exams, fees (single campus, up to 500 students)',
                    'amount' => 1200000,
                    'period' => '',
                    'price' => 'From TZS 1,200,000',
                ],
                [
                    'name' => 'ShuleXpert Standard',
                    'includes' => 'Full modules + parent portal + SMS alerts (up to 1,500 students)',
                    'amount' => 2200000,
                    'period' => '',
                    'price' => 'From TZS 2,200,000',
                ],
                [
                    'name' => 'ShuleXpert Enterprise',
                    'includes' => 'Multi-campus, advanced reporting, custom workflows & priority support',
                    'amount' => 3500000,
                    'period' => '',
                    'price' => 'From TZS 3,500,000',
                ],
                [
                    'name' => 'MauzoLink Starter',
                    'includes' => 'POS + inventory for retail / restaurant / SME (1 outlet, 2 users)',
                    'amount' => 750000,
                    'period' => '',
                    'price' => 'From TZS 750,000',
                ],
                [
                    'name' => 'MauzoLink Business',
                    'includes' => 'Multi-user POS, stock, sales reports, supplier tracking (up to 3 outlets)',
                    'amount' => 1500000,
                    'period' => '',
                    'price' => 'From TZS 1,500,000',
                ],
                [
                    'name' => 'WauminiLink',
                    'includes' => 'Church management: members, events, donations, communication tools',
                    'amount' => 900000,
                    'period' => '',
                    'price' => 'From TZS 900,000',
                ],
                [
                    'name' => 'PangishaLink',
                    'includes' => 'Hostel / property booking & occupancy management',
                    'amount' => 1100000,
                    'period' => '',
                    'price' => 'From TZS 1,100,000',
                ],
                [
                    'name' => 'SACCOSLink',
                    'includes' => 'SACCOS / cooperative: members, shares, loans, savings & reports (TCDC-ready)',
                    'amount' => 2000000,
                    'period' => '',
                    'price' => 'From TZS 2,000,000',
                ],
                [
                    'name' => 'Hotel / Custom System',
                    'includes' => 'Hotel, booking, or bespoke business system (scoped after consultation)',
                    'amount' => 1800000,
                    'period' => '',
                    'price' => 'From TZS 1,800,000',
                ],
                [
                    'name' => 'Annual Support Plan',
                    'includes' => 'Updates, bug fixes, remote support & system health checks',
                    'amount' => 300000,
                    'period' => '/ yr',
                    'price' => 'From TZS 300,000 / yr',
                ],
            ],
        ],

        'tourism-tools' => [
            'name' => 'Tourism Digital Solutions',
            'icon' => 'fas fa-map-marked-alt',
            'description' => 'Specialized software tools for safari operators, tour companies, lodges, and destination websites. Each tool can be delivered standalone or bundled into a Tourism Operator Portal.',
            'note' => 'Choosing the Tourism Tools Bundle saves vs. buying each tool separately. White-label branding for your tour company is included in the bundle.',
            'packages' => [
                [
                    'name' => 'Wildebeest Migration Tracker',
                    'includes' => 'Interactive map & calendar of Serengeti / Ngorongoro migration seasons with live-style updates for guests',
                    'amount' => 1500000,
                    'period' => '',
                    'price' => 'From TZS 1,500,000',
                ],
                [
                    'name' => 'Live Safari Budget Calculator',
                    'includes' => 'Dynamic quote tool: park fees, days, group size, vehicle & lodge options, instant client estimates',
                    'amount' => 1200000,
                    'period' => '',
                    'price' => 'From TZS 1,200,000',
                ],
                [
                    'name' => 'Best Time to Visit Finder',
                    'includes' => 'Smart recommendation engine by park, wildlife interest, weather & budget preferences',
                    'amount' => 950000,
                    'period' => '',
                    'price' => 'From TZS 950,000',
                ],
                [
                    'name' => 'Smart Safari Packing List',
                    'includes' => 'Personalized packing lists by season, trek type, altitude & trip duration (web / WhatsApp-ready)',
                    'amount' => 650000,
                    'period' => '',
                    'price' => 'From TZS 650,000',
                ],
                [
                    'name' => 'Kilimanjaro Route & Altitude Planner',
                    'includes' => 'Route comparison (Machame, Lemosho, Marangu, etc.), day-by-day altitude profile & acclimatization tips',
                    'amount' => 1350000,
                    'period' => '',
                    'price' => 'From TZS 1,350,000',
                ],
                [
                    'name' => 'Interactive National Park Explorer',
                    'includes' => 'Explore parks (Serengeti, Tarangire, Nyerere, etc.) with maps, highlights, animals & suggested itineraries',
                    'amount' => 1600000,
                    'period' => '',
                    'price' => 'From TZS 1,600,000',
                ],
                [
                    'name' => 'Tourism Tools Bundle (All 6)',
                    'includes' => 'All tools above integrated into one branded Tourism Panel + admin dashboard + training',
                    'amount' => 6500000,
                    'period' => '',
                    'price' => 'From TZS 6,500,000',
                ],
                [
                    'name' => 'Materuni / Attraction Booking',
                    'includes' => 'Custom waterfall / attraction booking system (as live on Tz-Pure Nature)',
                    'amount' => 1400000,
                    'period' => '',
                    'price' => 'From TZS 1,400,000',
                ],
            ],
        ],

        'graphics-design' => [
            'name' => 'Graphics Design',
            'icon' => 'fas fa-palette',
            'description' => 'Branding and marketing visuals that make your business memorable, from logos to print-ready banners and apparel mockups.',
            'packages' => [
                [
                    'name' => 'Logo Design',
                    'includes' => '3 concepts, 2 revision rounds, brand color guide & file formats (PNG, SVG, PDF)',
                    'amount' => 150000,
                    'period' => '',
                    'price' => 'From TZS 150,000',
                ],
                [
                    'name' => 'Brand Identity Kit',
                    'includes' => 'Logo, business cards, letterhead, social media kit & brand usage guide',
                    'amount' => 450000,
                    'period' => '',
                    'price' => 'From TZS 450,000',
                ],
                [
                    'name' => 'T-shirt Mockups Designing',
                    'includes' => 'Print-ready artwork + realistic mockups (front/back), up to 3 design concepts',
                    'amount' => 80000,
                    'period' => '',
                    'price' => 'From TZS 80,000',
                ],
                [
                    'name' => 'Posters',
                    'includes' => 'A3 / A2 / A1 event or promo poster, print-ready files, 2 revisions',
                    'amount' => 60000,
                    'period' => '',
                    'price' => 'From TZS 60,000',
                ],
                [
                    'name' => 'Tear / Rollup Banner Designing',
                    'includes' => 'Retractable roll-up (typically 85×200 cm) or tear drop banner design, print-ready',
                    'amount' => 100000,
                    'period' => '',
                    'price' => 'From TZS 100,000',
                ],
                [
                    'name' => 'Flyer / Brochure',
                    'includes' => 'Single or tri-fold marketing flyer with professional layout',
                    'amount' => 70000,
                    'period' => '',
                    'price' => 'From TZS 70,000',
                ],
                [
                    'name' => 'Social Media Graphics Pack',
                    'includes' => '10 branded posts / story templates for Facebook, Instagram & WhatsApp',
                    'amount' => 120000,
                    'period' => '',
                    'price' => 'From TZS 120,000',
                ],
                [
                    'name' => 'Certificate / ID Card Design',
                    'includes' => 'School or company certificate / staff ID card template',
                    'amount' => 50000,
                    'period' => '',
                    'price' => 'From TZS 50,000',
                ],
            ],
        ],

        'social-media-management' => [
            'name' => 'Social Media Management',
            'icon' => 'fas fa-share-alt',
            'description' => 'Setup, branding, and day-to-day management so your business stays visible, interactive, and trusted online.',
            'packages' => [
                [
                    'name' => 'Account Setup & Branding',
                    'includes' => 'Profile optimization, covers, bio & highlights for up to 3 platforms',
                    'amount' => 100000,
                    'period' => '',
                    'price' => 'From TZS 100,000',
                ],
                [
                    'name' => 'Starter Management',
                    'includes' => '8 posts/month, basic engagement, monthly performance summary',
                    'amount' => 250000,
                    'period' => '/ mo',
                    'price' => 'From TZS 250,000 / mo',
                ],
                [
                    'name' => 'Growth Management',
                    'includes' => '16 posts/month, stories, ads guidance, community replies, monthly report',
                    'amount' => 450000,
                    'period' => '/ mo',
                    'price' => 'From TZS 450,000 / mo',
                ],
                [
                    'name' => 'Premium Management',
                    'includes' => 'Daily content, ad campaigns, influencer coordination & detailed analytics',
                    'amount' => 750000,
                    'period' => '/ mo',
                    'price' => 'From TZS 750,000 / mo',
                ],
                [
                    'name' => 'Content Creation Only',
                    'includes' => 'Photography / design content pack without full page management',
                    'amount' => 180000,
                    'period' => '/ mo',
                    'price' => 'From TZS 180,000 / mo',
                ],
            ],
        ],

        'ict-consultancy' => [
            'name' => 'ICT Consultancy',
            'icon' => 'fas fa-lightbulb',
            'description' => 'Strategic guidance from assessment to implementation for smart digital transformation.',
            'packages' => [
                [
                    'name' => 'ICT Needs Assessment',
                    'includes' => 'On-site / remote audit of systems, risks & opportunities with written report',
                    'amount' => 350000,
                    'period' => '',
                    'price' => 'From TZS 350,000',
                ],
                [
                    'name' => 'Digital Transformation Plan',
                    'includes' => 'Roadmap, tool recommendations, budget plan & phased implementation timeline',
                    'amount' => 800000,
                    'period' => '',
                    'price' => 'From TZS 800,000',
                ],
                [
                    'name' => 'Process Automation Advisory',
                    'includes' => 'Workflow review & automation recommendations for schools / SMEs / NGOs',
                    'amount' => 500000,
                    'period' => '',
                    'price' => 'From TZS 500,000',
                ],
                [
                    'name' => 'Half-day Consultation',
                    'includes' => 'Focused strategy session with actionable next steps',
                    'amount' => 150000,
                    'period' => '',
                    'price' => 'From TZS 150,000',
                ],
                [
                    'name' => 'Full-day On-site Consulting',
                    'includes' => 'Hands-on consulting at your premises (Moshi & nearby regions)',
                    'amount' => 280000,
                    'period' => '',
                    'price' => 'From TZS 280,000',
                ],
            ],
        ],

        'ict-infrastructure' => [
            'name' => 'ICT Infrastructure',
            'icon' => 'fas fa-server',
            'description' => 'Design, supply, installation, and management of reliable, secure technology environments. Equipment costs are quoted separately based on brand and quantity.',
            'packages' => [
                [
                    'name' => 'Structured Cabling (per point)',
                    'includes' => 'Network point installation, labor & termination (cable/materials extra)',
                    'amount' => 45000,
                    'period' => '/ pt',
                    'price' => 'From TZS 45,000 / pt',
                ],
                [
                    'name' => 'Office Network Setup',
                    'includes' => 'Router, Wi-Fi, LAN config, sharing & basic firewall for small office',
                    'amount' => 350000,
                    'period' => '',
                    'price' => 'From TZS 350,000',
                ],
                [
                    'name' => 'Server Setup & Virtualization',
                    'includes' => 'Physical / virtual server install, roles, users & security hardening',
                    'amount' => 600000,
                    'period' => '',
                    'price' => 'From TZS 600,000',
                ],
                [
                    'name' => 'Cloud Hosting Setup',
                    'includes' => 'Cloud server provisioning, migration & SSL for apps / websites',
                    'amount' => 250000,
                    'period' => '',
                    'price' => 'From TZS 250,000',
                ],
                [
                    'name' => 'Backup & Disaster Recovery',
                    'includes' => 'Automated backup schedule, recovery testing & documentation',
                    'amount' => 400000,
                    'period' => '',
                    'price' => 'From TZS 400,000',
                ],
                [
                    'name' => 'CCTV / Security Network',
                    'includes' => 'IP camera network design & installation support (hardware quoted separately)',
                    'amount' => 500000,
                    'period' => '',
                    'price' => 'From TZS 500,000',
                ],
                [
                    'name' => 'Infrastructure Support Retainer',
                    'includes' => 'Monthly remote monitoring & priority on-site response',
                    'amount' => 200000,
                    'period' => '/ mo',
                    'price' => 'From TZS 200,000 / mo',
                ],
            ],
        ],

        'computer-maintenance' => [
            'name' => 'Computer Maintenance',
            'icon' => 'fas fa-tools',
            'description' => 'Keep desktops, laptops, and office machines running smoothly, preventive care, repairs, and ongoing support for homes, schools, and businesses.',
            'packages' => [
                [
                    'name' => 'PC / Laptop Diagnosis',
                    'includes' => 'Full hardware & software health check with written findings',
                    'amount' => 25000,
                    'period' => '',
                    'price' => 'From TZS 25,000',
                ],
                [
                    'name' => 'Software Installation & Cleanup',
                    'includes' => 'OS updates, drivers, antivirus, junk removal & speed optimization',
                    'amount' => 40000,
                    'period' => '',
                    'price' => 'From TZS 40,000',
                ],
                [
                    'name' => 'Virus / Malware Removal',
                    'includes' => 'Deep scan, cleanup, security hardening & recovery assistance',
                    'amount' => 50000,
                    'period' => '',
                    'price' => 'From TZS 50,000',
                ],
                [
                    'name' => 'Hardware Repair Labor',
                    'includes' => 'Screen, keyboard, RAM, HDD/SSD replacement labor (parts extra)',
                    'amount' => 60000,
                    'period' => '',
                    'price' => 'From TZS 60,000',
                ],
                [
                    'name' => 'Data Backup / Recovery Assist',
                    'includes' => 'File backup setup or assisted recovery of recoverable data',
                    'amount' => 70000,
                    'period' => '',
                    'price' => 'From TZS 70,000',
                ],
                [
                    'name' => 'On-site Visit (Moshi)',
                    'includes' => 'Technician visit within Moshi Municipality (first hour)',
                    'amount' => 35000,
                    'period' => '',
                    'price' => 'From TZS 35,000',
                ],
                [
                    'name' => 'School / Office Contract',
                    'includes' => 'Monthly maintenance for up to 10 machines, cleaning, updates, priority support',
                    'amount' => 250000,
                    'period' => '/ mo',
                    'price' => 'From TZS 250,000 / mo',
                ],
                [
                    'name' => 'Annual PC Care Plan (1 device)',
                    'includes' => '2 preventive visits/year + remote support priority',
                    'amount' => 120000,
                    'period' => '/ yr',
                    'price' => 'From TZS 120,000 / yr',
                ],
            ],
        ],
    ],
];
