<?php

/**
 * Editable site image slots managed from /admin/site-images.
 * path in DB overrides default_path when set.
 * width/height are recommended pixel sizes matching current defaults.
 */
return [
    'groups' => [
        'brand' => 'Brand & Logo',
        'hero' => 'Homepage Hero',
        'home' => 'Homepage Sections',
        'about' => 'About Page',
        'banners' => 'Page Banners',
        'shared' => 'Shared Widgets',
    ],

    'slots' => [
        'logo' => [
            'label' => 'Site Logo',
            'group' => 'brand',
            'default' => 'images/logo_header.png',
            'width' => 200,
            'height' => 160,
            'sort' => 10,
        ],
        'hero_1' => [
            'label' => 'Hero Slide 1',
            'group' => 'hero',
            'default' => 'images/Banner_hero1.jpg',
            'width' => 1920,
            'height' => 813,
            'sort' => 20,
        ],
        'hero_2' => [
            'label' => 'Hero Slide 2',
            'group' => 'hero',
            'default' => 'images/Banner_hero2.jpg',
            'width' => 1920,
            'height' => 813,
            'sort' => 21,
        ],
        'hero_3' => [
            'label' => 'Hero Slide 3',
            'group' => 'hero',
            'default' => 'images/Banner_hero3.jpg',
            'width' => 1920,
            'height' => 813,
            'sort' => 22,
        ],
        'hero_4' => [
            'label' => 'Hero Slide 4',
            'group' => 'hero',
            'default' => 'images/Banner_hero4.jpg',
            'width' => 1920,
            'height' => 813,
            'sort' => 23,
        ],
        'home_about_1' => [
            'label' => 'Home About Image (main)',
            'group' => 'home',
            'default' => 'images/About1.jpg',
            'width' => 437,
            'height' => 530,
            'sort' => 30,
        ],
        'home_about_2' => [
            'label' => 'Home About Image (secondary)',
            'group' => 'home',
            'default' => 'images/About2.jpg',
            'width' => 269,
            'height' => 277,
            'sort' => 31,
        ],
        'home_video_banner' => [
            'label' => 'Home Video / Server Banner',
            'group' => 'home',
            'default' => 'images/image1.jpg',
            'width' => 1920,
            'height' => 800,
            'sort' => 32,
        ],
        'home_why_2' => [
            'label' => 'Why Choose Us Image 2',
            'group' => 'home',
            'default' => 'images/why2.jpg',
            'width' => 270,
            'height' => 235,
            'sort' => 33,
        ],
        'home_why_3' => [
            'label' => 'Why Choose Us Image 3',
            'group' => 'home',
            'default' => 'images/why3.jpg',
            'width' => 400,
            'height' => 530,
            'sort' => 34,
        ],
        'home_why_4' => [
            'label' => 'Why Choose Us Image 4',
            'group' => 'home',
            'default' => 'images/why4.jpg',
            'width' => 400,
            'height' => 530,
            'sort' => 35,
        ],
        'home_live_solutions_bg' => [
            'label' => 'Live Solutions Background',
            'group' => 'home',
            'default' => 'images/server1.jpg',
            'width' => 1920,
            'height' => 800,
            'sort' => 36,
        ],
        'about_hero' => [
            'label' => 'About Page Banner',
            'group' => 'about',
            'default' => 'images/about-hero.png',
            'width' => 1854,
            'height' => 848,
            'sort' => 40,
        ],
        'about_1' => [
            'label' => 'About Page Image 1',
            'group' => 'about',
            'default' => 'images/About1.jpg',
            'width' => 437,
            'height' => 530,
            'sort' => 41,
        ],
        'about_2' => [
            'label' => 'About Page Image 2',
            'group' => 'about',
            'default' => 'images/About2.jpg',
            'width' => 269,
            'height' => 277,
            'sort' => 42,
        ],
        'banner_services' => [
            'label' => 'Services Page Banner',
            'group' => 'banners',
            'default' => 'images/Service_banner.jpg',
            'width' => 1920,
            'height' => 440,
            'sort' => 50,
        ],
        'banner_solutions' => [
            'label' => 'Solutions Page Banner',
            'group' => 'banners',
            'default' => 'images/Solution.jpg',
            'width' => 1920,
            'height' => 440,
            'sort' => 51,
        ],
        'banner_team' => [
            'label' => 'Team Page Banner',
            'group' => 'banners',
            'default' => 'images/team.jpg',
            'width' => 1920,
            'height' => 440,
            'sort' => 52,
        ],
        'banner_blog' => [
            'label' => 'Blog / News Banner',
            'group' => 'banners',
            'default' => 'images/blog.jpg',
            'width' => 1920,
            'height' => 440,
            'sort' => 53,
        ],
        'banner_blog_details' => [
            'label' => 'Blog Details Banner',
            'group' => 'banners',
            'default' => 'images/blogs_details.jpg',
            'width' => 1920,
            'height' => 440,
            'sort' => 54,
        ],
        'banner_contact' => [
            'label' => 'Contact Page Banner',
            'group' => 'banners',
            'default' => 'images/Contact.jpg',
            'width' => 1920,
            'height' => 440,
            'sort' => 55,
        ],
        'banner_faq' => [
            'label' => 'FAQ Page Banner',
            'group' => 'banners',
            'default' => 'images/Faq_banner.jpg',
            'width' => 1920,
            'height' => 440,
            'sort' => 56,
        ],
        'banner_pricing' => [
            'label' => 'Pricing Page Banner',
            'group' => 'banners',
            'default' => 'images/Service_banner.jpg',
            'width' => 1920,
            'height' => 440,
            'sort' => 57,
        ],
        'cta_services' => [
            'label' => 'Services CTA Background',
            'group' => 'banners',
            'default' => 'images/Digital Growth.jpg',
            'width' => 920,
            'height' => 500,
            'sort' => 58,
        ],
        'cta_solutions' => [
            'label' => 'Solutions CTA Background',
            'group' => 'banners',
            'default' => 'images/Business Operations.jpg',
            'width' => 920,
            'height' => 500,
            'sort' => 59,
        ],
        'need_help' => [
            'label' => 'Need Help / Customer Care',
            'group' => 'shared',
            'default' => 'images/customercare.png',
            'width' => 1280,
            'height' => 1228,
            'sort' => 70,
        ],
    ],
];
