<?php

return [
    'members' => [
        'caroline-shija' => [
            'name' => 'Caroline Shija',
            'role' => 'Managing Director',
            'image' => 'images/Caroline-shija.jpg',
            'email' => 'caroline@emca.tech',
            'mobile' => '+255 749 719 998',
            'style' => 'style-2',
            'delay' => '.3s',
            'bio' => [
                'Caroline Shija serves as Managing Director at EmCa Techonologies LTD, providing strategic leadership across the company\'s technology and digital solutions portfolio.',
                'She oversees business operations, client partnerships, and service delivery, ensuring EmCa remains focused on practical, reliable solutions for schools, businesses, and institutions.',
                'With a strong commitment to innovation and customer success, Caroline helps guide teams that build software, ICT infrastructure, and creative digital services.',
            ],
            'social' => [
                'instagram' => '#',
                'facebook' => '#',
                'linkedin' => '#',
            ],
            'cv' => 'cv/caroline-shija.pdf',
        ],
        'mariana-swai' => [
            'name' => 'Mariana Swai',
            'role' => 'Accountant',
            'image' => 'images/Mariana-swai.jpg',
            'email' => 'mariana@emca.tech',
            'mobile' => '+255 749 719 998',
            'style' => '',
            'delay' => '.5s',
            'bio' => [
                'Mariana Swai is the Accountant at EmCa Techonologies LTD, responsible for financial planning, reporting, and day-to-day accounting operations.',
                'She supports transparent financial management and helps keep projects and services running efficiently through accurate records and budgeting.',
                'Mariana works closely with management and project teams to maintain financial discipline across the organization.',
            ],
            'social' => [
                'instagram' => '#',
                'facebook' => '#',
                'linkedin' => '#',
            ],
            'cv' => 'cv/mariana-swai.pdf',
        ],
        'ofeni-mwakapola' => [
            'name' => 'Ofeni Mwakapola',
            'role' => 'System Developer',
            'image' => 'images/often.jpg',
            'email' => 'ofeni.fred@emca.tech',
            'mobile' => '+255 744 341 239',
            'style' => 'style-2',
            'delay' => '.7s',
            'bio' => [
                'Ofeni Mwakapola is a System Developer at EmCa Techonologies LTD and a graduate with a Bachelor of Business Information and Communication Technology from Moshi Co-operative University (MoCU). He brings strong practical experience in web development, database management, Laravel, WordPress, and ICT support services.',
                'He has a proven ability to design and develop real-world digital solutions, including management systems and professional websites that help organizations work more efficiently. He is passionate about using technology to solve business challenges and support digital transformation.',
                'At EmCa, he contributes to products such as Wauminilink and other custom platforms, combining technical expertise with problem-solving and a commitment to continuous professional growth in Information and Communication Technology.',
            ],
            'social' => [
                'instagram' => 'https://www.instagram.com/oftenfred_official?igsh=MWxwNnJ2OWd1ODJncQ==',
                'facebook' => 'https://www.facebook.com/share/1Hx2bNQfkq/',
                'github' => 'https://github.com/oftenfredict-source',
            ],
            'cv' => 'cv/ofeni-mwakapola.pdf',
        ],
        'leonard-kingoye' => [
            'name' => 'Leonard Kingoye',
            'role' => 'Graphics Designer',
            'image' => 'images/Leonard.jpg',
            'email' => 'leonard@emca.tech',
            'mobile' => '+255 749 719 998',
            'style' => '',
            'delay' => '.9s',
            'bio' => [
                'Leonard Kingoye is the Graphics Designer at EmCa Techonologies LTD, creating visual identities, marketing materials, and digital brand assets.',
                'He combines creative design with clear communication to help clients present their services professionally across print and online channels.',
                'Leonard supports branding, social media visuals, and product interfaces that strengthen EmCa\'s and clients\' public image.',
            ],
            'social' => [
                'instagram' => '#',
                'facebook' => '#',
                'linkedin' => '#',
            ],
            'cv' => 'cv/leonard-kingoye.pdf',
        ],
        'hassani-s-hassani' => [
            'name' => 'Hassani S. Hassani',
            'role' => 'System Developer',
            'image' => 'images/Hassan Said .jpg',
            'email' => 'hassani@emca.tech',
            'mobile' => '+255 749 719 998',
            'style' => 'style-2',
            'delay' => '.2s',
            'bio' => [
                'Hassani S. Hassani is a System Developer at EmCa Techonologies LTD, focused on building reliable software systems for schools and enterprises.',
                'He develops backend logic, database structures, and application features that support efficient day-to-day operations.',
                'Hassani is committed to secure, maintainable code and collaborative development practices across EmCa\'s product teams.',
            ],
            'social' => [
                'instagram' => '#',
                'facebook' => '#',
                'github' => '#',
            ],
            'cv' => 'cv/hassani-s-hassani.pdf',
        ],
        'benjamini-bufumbe' => [
            'name' => 'Benjamini Bufumbe',
            'role' => 'Business Analyst',
            'image' => 'images/benjamini-bufumbe.jpg',
            'email' => 'benjamini@emca.tech',
            'mobile' => '+255 749 719 998',
            'style' => '',
            'delay' => '.4s',
            'bio' => [
                'Benjamini Bufumbe is a Business Analyst at EmCa Techonologies LTD, bridging client needs with technical solutions through research, documentation, and process design.',
                'He helps define system requirements, workflows, and improvement opportunities for schools, SMEs, and institutional clients.',
                'Benjamini supports project planning and stakeholder communication to ensure delivered solutions match real operational needs.',
            ],
            'social' => [
                'instagram' => '#',
                'facebook' => '#',
                'linkedin' => '#',
            ],
            'cv' => 'cv/benjamini-bufumbe.pdf',
        ],
        'issa-nassoro' => [
            'name' => 'Issa Nassoro',
            'role' => 'System Developer',
            'image' => 'images/issa-nassoro.jpg',
            'email' => 'issa@emca.tech',
            'mobile' => '+255 749 719 998',
            'style' => 'style-2',
            'delay' => '.6s',
            'bio' => [
                'Issa Nassoro is a System Developer at EmCa Techonologies LTD, working on custom applications and integrated digital platforms.',
                'He focuses on scalable architecture, API development, and performance optimization for client-facing systems.',
                'Issa helps deliver software that is practical, secure, and aligned with EmCa\'s standards for quality and support.',
            ],
            'social' => [
                'instagram' => '#',
                'facebook' => '#',
                'github' => '#',
            ],
            'cv' => 'cv/issa-nassoro.pdf',
        ],
        'ashery-aron' => [
            'name' => 'Ashery Aron',
            'role' => 'System Developer',
            'image' => 'images/Ashery Aron.jpg',
            'email' => 'ashery@emca.tech',
            'mobile' => '+255 749 719 998',
            'style' => '',
            'delay' => '.8s',
            'bio' => [
                'Ashery Aron is a System Developer at EmCa Techonologies LTD, contributing to web applications and internal tools used across the company\'s service lines.',
                'He works on feature development, testing, and deployment support for education and business management systems.',
                'Ashery values clean implementation, teamwork, and continuous improvement in every project he delivers.',
            ],
            'social' => [
                'instagram' => '#',
                'facebook' => '#',
                'github' => '#',
            ],
            'cv' => 'cv/ashery-aron.pdf',
        ],
        'ally-h-ally' => [
            'name' => 'Ally H. Ally',
            'role' => 'System Developer',
            'image' => 'images/Ally Ally.jpg',
            'email' => 'ally@emca.tech',
            'mobile' => '+255 616 775 800',
            'style' => 'style-2',
            'delay' => '.2s',
            'bio' => [
                'Ally H. Ally is a System Developer at EmCa Techonologies LTD, building software solutions that simplify operations for schools and organizations.',
                'He develops and maintains application modules, integrations, and user-facing features with attention to reliability and usability.',
                'Ally supports EmCa\'s mission to deliver technology that is accessible, efficient, and tailored to local client needs.',
            ],
            'social' => [
                'instagram' => '#',
                'facebook' => '#',
                'github' => '#',
            ],
            'cv' => 'cv/ally-h-ally.pdf',
        ],
    ],
];
